In [12]:
'''
Program creates an array & uses indexing and slicing techniques to perform basic operations
Author: Sanjay Reddy Muthyala
'''

'\nProgram creates an array & uses indexing and slicing techniques to perform basic operations\nAuthor: Sanjay Reddy Muthyala\n'

In [13]:
import numpy as np

In [16]:
def main():
    #creating an array of len 15.
    arr = np.arange(1,16)
    #Reshaping into 3-by-5 array.
    arr = arr.reshape(3,5)
    print('Array after reshaping: \n',arr)
    #numbers at row 2.
    print('\nElememts at row 2: ',arr[2,:])
    #numbers at column 4.
    print('\nElements at column 4: ',arr[:,4])
    #numbers at rows 0 and 1
    print('\nElements at rows 0 and 1: ',arr[0:2,:])
    #numbers at columns 2-4.
    print('\nElememts at columns 2-4: ',arr[:,2:5])
    #number at row 1 and column 4
    print('\nElement at row 1 and column 4: ',arr[1,4])
    
    #select element in rows 1 and 2 that are in columns 0,2 and 4
    print('\nElements at row 1 and 2 that are in column 0: ',arr[1:3,0])
    print('\nElements at row 1 and 2 that are in column 2: ',arr[1:3,2])
    print('\nElements at row 1 and 2 that are in column 4: ',arr[1:3,4])
main()

Array after reshaping: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Elememts at row 2:  [11 12 13 14 15]

Elements at column 4:  [ 5 10 15]

Elements at rows 0 and 1:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Elememts at columns 2-4:  [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]

Element at row 1 and column 4:  10

Elements at row 1 and 2 that are in column 0:  [ 6 11]

Elements at row 1 and 2 that are in column 2:  [ 8 13]

Elements at row 1 and 2 that are in column 4:  [10 15]
